name:Deploy Parking App

on:
:push:
branches:[main]

jobs:
 deploy:
  runs on:ubuntu:latest
  steps:
  -uses:actions/checkout@v4
  -name:Deploy To GitHub Pages
  uses:peaceiris/actions-gh-pagesv4
  with:
   github_token:$
   {{secrets.GITHUB_TOKEN}}
        publish_dir:./public
   
